export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const FULL_SCREEN = 'FULL_SCREEN';
export const FULL_SCREEN_EXIT = 'FULL_SCREEN_EXIT';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const CHANGE_SUB_LAYOUT = 'CHANGE_SUB_LAYOUT';
export const LAYOUT_TYPE = 'LAYOUT_TYPE';
export const RESET = 'RESET';
export const NAV_BACK_COLOR = 'NAV_BACK_COLOR';
export const NAV_BRAND_COLOR = 'NAV_BRAND_COLOR';
export const HEADER_BACK_COLOR = 'HEADER_BACK_COLOR';
export const RTL_LAYOUT = 'RTL_LAYOUT';
export const NAV_FIXED_LAYOUT = 'NAV_FIXED_LAYOUT';
export const HEADER_FIXED_LAYOUT = 'HEADER_FIXED_LAYOUT';
export const BOX_LAYOUT = 'BOX_LAYOUT';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';
export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';

//Login
export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';

//TANK LIST
export const GET_TANK_LIST = 'GET_TANK_LIST';
export const GET_LC_LIST = 'GET_LC_LIST';
export const GET_TANK_DETAILS = 'GET_TANK_DETAILS';
export const SAVE_RECORD_STATUS = 'SAVE_RECORD_STATUS';
export const UPDATE_RECORD_STATUS = 'UPDATE_RECORD_STATUS';
export const LC_DELETE_RECORD_STATUS = 'LC_DELETE_RECORD_STATUS';
export const LC_COPY_RECORD_STATUS = 'LC_COPY_RECORD_STATUS0';
export const CLEAR_ALL_TANK_DATA = 'CLEAR_ALL_TANK_DATA';
export const ERROR = 'ERROR';

//VESSEL LIST
export const GET_VESSEL_LIST = 'GET_VESSEL_LIST';
export const CLEAR_ALL_VESSEL_DATA = 'CLEAR_ALL_VESSEL_DATA';

export const GET_FW_LIST = 'GET_FW_LIST';
export const DELETE_RECORD_STATUS = "DELETE_RECORD_STATUS"
export const CLEAR_ALL_FW_DATA = "CLEAR_ALL_FW_DATA";